global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web_app'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

